### ISSUE TITLE
books bucket is not getting created

### ISSUE THREAD

**Issue by jchowdhary** [arun-gupta/oreilly-docker-book#1]
HI Arun, I am configuring your project locally and I must add that i am running docker on Windows.To get this project running, i needed to edit the couchbase/configure-node.sh file...here i needed to replace all 127.0.0.1 with the IP which is exposed to host from my container ie. 192.168.99.100.
 So when i run the "docker-compose up -d", it starts both the containers but when i hit the url in my browser i.e. "http://192.168.99.100:8080" or "http://192.168.99.100:8080/books" i get the below logs
`[36mweb_1  |[0m [0m[33m19:02:18,975 WARN  [com.couchbase.client.core.endpoint.Endpoint] (cb-io-1-1) [null][KeyValueEndpoint]: Authentication Failure.
[36mweb_1  |[0m [0m[31m19:02:19,698 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 68) MSC000001: Failed to start service jboss.deployment.unit."books.war".component.Database.START: org.jboss.msc.service.StartException in service jboss.deployment.unit."books.war".component.Database.START: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
[36mweb_1  |[0m       at org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:57)
[36mweb_1  |[0m       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[36mweb_1  |[0m       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36mweb_1  |[0m       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[36mweb_1  |[0m       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[36mweb_1  |[0m       at java.lang.Thread.run(Thread.java:745)
[36mweb_1  |[0m       at org.jboss.threads.JBossThread.run(JBossThread.java:320)
[36mweb_1  |[0m Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
[36mweb_1  |[0m       at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:163)
[36mweb_1  |[0m       at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:134)
[36mweb_1  |[0m       at org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:88)
[36mweb_1  |[0m       at org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:124)
[36mweb_1  |[0m       at org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:138)
[36mweb_1  |[0m       at org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:54)
[36mweb_1  |[0m       ... 6 more
[36mweb_1  |[0m Caused by: javax.ejb.EJBException: com.couchbase.client.java.error.BucketDoesNotExistException: Bucket "books" does not exist.
[36mweb_1  |[0m       at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:187)`

Can you pls. suggest what configuration is wrong here..

**Comment by arun-gupta** [comment]
The bucket `books` needs to be explicitly created.

It can be created using Couchbase Web Console as explained at https://developer.couchbase.com/documentation/server/current/clustersetup/create-bucket.html.
